[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.flash_size = 4MB
board_build.partitions = default.csv

lib_deps =
  bodmer/TFT_eSPI
  bitbank2/AnimatedGIF
  paulstoffregen/XPT2046_Touchscreen
