name: Build BIN

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PlatformIO
        uses: platformio/action@v2

      - name: Build firmware
        run: pio run
